Tesla_Balance_Sheet

In [21]:
import pandas as pd

# Create a DataFrame for the balance sheet data
balance_sheet_data = {
    "Description": [
        "Cash and cash equivalents", "Accounts receivable, net", "Inventory", "Prepaid expenses and other current assets",
        "Total current assets", "Operating lease vehicles, net", "Solar energy systems, net", "Property, plant and equipment, net",
        "Operating lease right-of-use assets", "Goodwill and intangible assets, net", "Other non-current assets",
        "Total assets", "Accounts payable", "Accrued liabilities and other", "Deferred revenue", "Customer deposits",
        "Current portion of debt and finance leases", "Total current liabilities", "Debt and finance leases, net of current portion",
        "Deferred revenue, net of current portion", "Other long-term liabilities", "Total liabilities",
        "Redeemable noncontrolling interests in subsidiaries", "Convertible senior notes", "Total stockholders' equity",
        "Noncontrolling interests in subsidiaries", "Total liabilities and equity"
    ],
    "31-Dec-19": [
        6268, 1324, 3552, 959, 12103, 2447, 6138, 10396, 1218, 537, 1470, 34309, 3771, 3222, 1163, 726, 1785, 10667, 11634,
        1207, 2691, 26199, 643, 0, 6618, 849, 34309
    ],
    "31-Mar-20": [
        8080, 1274, 4494, 1045, 14893, 2527, 6106, 10638, 1197, 516, 1373, 37250, 3970, 2825, 1186, 788, 3217, 11986,
        10666, 1199, 2667, 26518, 632, 60, 9173, 869, 37250
    ],
    "30-Jun-20": [
        8615, 1485, 4018, 1218, 15336, 2524, 6069, 11009, 1274, 508, 1415, 38135, 3638, 3110, 1130, 713, 3679, 12270,
        10416, 1198, 2870, 26754, 613, 44, 9855, 869, 38135
    ],
    "30-Sep-20": [
        14531, 1757, 4218, 1238, 21744, 2742, 6025, 11848, 1375, 521, 1436, 45691, 4958, 3252, 1258, 708, 3126, 13302,
        10559, 1233, 3049, 28143, 608, 48, 16031, 861, 45691
    ],
    "31-Dec-20": [
        19384, 1886, 4101, 1346, 26717, 3091, 5979, 12747, 1558, 520, 1536, 52148, 6051, 3855, 1458, 752, 2132, 14248,
        9556, 1284, 3330, 28418, 604, 51, 22225, 850, 52148
    ]
}

# Convert to DataFrame
balance_sheet_df = pd.DataFrame(balance_sheet_data)

# Save DataFrame to CSV
balance_sheet_file_path = "balance_sheet_2020.csv"
balance_sheet_df.to_csv(balance_sheet_file_path, index=False)

balance_sheet_file_path

'balance_sheet_2020.csv'

In [22]:
# Create a DataFrame for the balance sheet data
balance_sheet_data_2021 = {
    "Description": [
        "Cash and cash equivalents", "Short-term marketable securities", "Accounts receivable, net", "Inventory",
        "Prepaid expenses and other current assets", "Total current assets", "Operating lease vehicles, net",
        "Solar energy systems, net", "Property, plant and equipment, net", "Operating lease right-of-use assets",
        "Digital assets, net", "Goodwill and intangible assets, net", "Other non-current assets",
        "Total assets", "Accounts payable", "Accrued liabilities and other", "Deferred revenue", "Customer deposits",
        "Current portion of debt and finance leases", "Total current liabilities", "Debt and finance leases, net of current portion",
        "Deferred revenue, net of current portion", "Other long-term liabilities", "Total liabilities",
        "Redeemable noncontrolling interests in subsidiaries", "Convertible senior notes", "Total stockholders' equity",
        "Noncontrolling interests in subsidiaries", "Total liabilities and equity", "Vehicle and energy product financing (non-recourse)",
        "Other non-recourse debt", "Recourse debt", "Total debt excluding vehicle and energy product financing",
        "Days sales outstanding", "Days payable outstanding"
    ],
    "31-Dec-20": [
        19384, None, 1886, 4101, 1346, 26717, 3091, 5979, 12747, 1558, 520, 1536, None, 52148, 6051, 3855, 1458, 752, 2132, 14248, 9556, 1284,
        3330, 28418, 604, None, 22225, 850, None, 3930, 630, 5660, 6290, 16, 58
    ],
    "31-Mar-21": [
        17141, None, 1890, 4132, 1542, 24705, 3396, 5933, 13868, 1647, 1331, 505, 1587, 52972, 6648, 4073, 1592, 745, 1819, 14877, 9053, 1294,
        3283, 28507, 601, None, 23017, 847, None, 4323, 628, 4483, None, 16, 70
    ],
    "30-Jun-21": [
        16229, None, 2129, 4733, 1602, 24693, 3748, 5883, 15665, 1734, 1311, 486, 1626, 55146, 7558, 4778, 1693, 812, 1530, 16371, 7871, 1318,
        3336, 28896, 605, None, 24804, 841, None, 3969, None, 3977, 3991, None, None
    ],
    "30-Sep-21": [
        16065, 30, 1962, 5199, 1746, 25002, 4167, 5821, 17298, 1962, 1260, 470, 1854, 57834, 8260, 5443, 1801, 831, 1716, 18051, 6438, 1365,
        3486, 29340, 605, None, 27053, 836, None, 4531, 14, 2101, 215, 14, 72
    ],
    "31-Dec-21": [
        17576, 131, 1913, 5757, 1723, 27100, 4511, 5765, 18884, 2016, 1260, 457, 2138, 62131, 10025, 5719, 1447, None, 1589, 19705, 5245,
        None, 3546, 30548, 568, None, 30189, 826, None, 3952, 14, 1376, 1390, 10, 65
    ]
}

# Convert to DataFrame
balance_sheet_df_2021 = pd.DataFrame(balance_sheet_data_2021)

# Save DataFrame to CSV
balance_sheet_file_path_2021 = "balance_sheet_2021.csv"
balance_sheet_df_2021.to_csv(balance_sheet_file_path_2021, index=False)

balance_sheet_file_path_2021

'balance_sheet_2021.csv'

In [23]:
# Create a DataFrame for the balance sheet data
balance_sheet_data_2022 = {
    "Description": [
        "Cash, cash equivalents and investments", "Accounts receivable, net", "Inventory",
        "Prepaid expenses and other current assets", "Total current assets", "Operating lease vehicles, net",
        "Solar energy systems, net", "Property, plant and equipment, net", "Operating lease right-of-use assets",
        "Digital assets, net", "Goodwill and intangible assets, net", "Other non-current assets",
        "Total assets", "Accounts payable", "Accrued liabilities and other", "Deferred revenue",
        "Customer deposits", "Current portion of debt and finance leases", "Total current liabilities",
        "Debt and finance leases, net of current portion", "Deferred revenue, net of current portion",
        "Other long-term liabilities", "Total liabilities", "Redeemable noncontrolling interests in subsidiaries",
        "Total stockholders' equity", "Noncontrolling interests in subsidiaries", "Total liabilities and equity",
        "Vehicle and energy product financing (non-recourse)", "Other non-recourse debt", "Recourse debt",
        "Total debt excluding vehicle and energy product financing", "Days sales outstanding", "Days payable outstanding"
    ],
    "31-Dec-21": [
        17707, 1913, 5757, 1723, 27100, 4511, 5765, 18884, 2016, 1260, 457, 2138, 62131, 10025, 5719, 1447, 925, 1589,
        19705, 5245, 2052, 3546, 30548, 568, 30189, 826, 62131, 3952, None, 1376, 1390, 10, 65
    ],
    "31-Mar-22": [
        18013, 2301, 6691, 2035, 29050, 4745, 5686, 20027, 2181, 1261, 454, 2634, 66038, 11171, 5906, 1594, 1125, 1659,
        21455, 3153, 2185, 3839, 30632, 459, 34085, 862, 66038, 3333, None, 74, 88, 10, 72
    ],
    "30-Jun-22": [
        18915, 2081, 8108, 218, 31222, 4782, 5624, 21093, 2185, 218, 437, 2952, 68513, 11212, 6037, 1858, 1182, 1532,
        21821, 2898, 2210, 3926, 30855, 421, 36376, 861, 68513, 3086, 13, 53, 66, 12, 80
    ],
    "30-Sep-22": [
        21107, 2192, 10327, 2364, 35990, 4824, 5562, 21926, 2251, 218, 419, 3236, 74426, 13897, 6246, 1928, 1083, 1457,
        24611, 2096, 2265, 4330, 33302, 421, 39851, 852, 74426, 2335, None, None, None, None, None
    ],
    "31-Dec-22": [
        22185, 2952, 12839, 2941, 40917, 5035, 5489, 23548, 2563, 184, 409, 4193, 82338, 15255, 7142, 1747, 1063, 1502,
        26709, 1597, 2808, 5330, 36440, 409, 44851, 785, 82338, 2001, None, None, None, None, None
    ]
}

# Convert to DataFrame
balance_sheet_df_2022 = pd.DataFrame(balance_sheet_data_2022)

# Save DataFrame to CSV
balance_sheet_file_path_2022 = "balance_sheet_2022.csv"
balance_sheet_df_2022.to_csv(balance_sheet_file_path_2022, index=False)

balance_sheet_file_path_2022

'balance_sheet_2022.csv'

In [24]:
# Load the CSV files
csv_2020_path = "balance_sheet_2020.csv"
csv_2021_path = "balance_sheet_2021.csv"
csv_2022_path = "balance_sheet_2022.csv"

df_2020 = pd.read_csv(csv_2020_path)
df_2021 = pd.read_csv(csv_2021_path)
df_2022 = pd.read_csv(csv_2022_path)

# Combine the dataframes
combined_df = pd.concat([df_2020, df_2021, df_2022])

# Remove duplicates
combined_df = combined_df.drop_duplicates()

# Save the combined dataframe to a new CSV file
combined_csv_path = "balance_sheet.csv"
combined_df.to_csv(combined_csv_path, index=False)

combined_csv_path

'balance_sheet.csv'

Tesla_Cash_Flow

In [25]:
# Clean and organize the extracted text into structured data
cash_flow_data = {
    "Description": [
        "Net income",
        "Adjustments to reconcile net income to net cash provided by (used in) operating activities:",
        "Depreciation, amortization and impairment",
        "Stock-based compensation",
        "Other",
        "Changes in operating assets and liabilities, net of effect of business combinations",
        "Net cash provided by (used in) operating activities",
        "Capital expenditures",
        "Purchases of solar energy systems, net of sales",
        "Purchase of intangible assets",
        "Receipt of government grants",
        "Business combinations, net of cash acquired",
        "Net cash used in investing activities",
        "Net cash flows from debt activities",
        "Collateralized lease repayments",
        "Net borrowings (repayments) under vehicle and solar financing",
        "Net cash flows from noncontrolling interests - Auto",
        "Net cash flows from noncontrolling interests - Solar",
        "Proceeds from issuances of common stock in public offerings, net of issuance costs",
        "Other",
        "Net cash (used in) provided by financing activities",
        "Effect of exchange rate changes on cash and cash equivalents and restricted cash",
        "Net increase in cash and cash equivalents and restricted cash",
        "Cash and cash equivalents and restricted cash at beginning of period",
        "Cash and cash equivalents and restricted cash at end of period"
    ],
    "Q4-2019": [
        132, None, 577, 281, 204, 231, 1425, -412, -37, None, 46, None, -403, -591, -87, 478, 19, 6, None, 96, 14, 957, 5826, 6783
    ],
    "Q1-2020": [
        68, None, 553, 211, 175, -1447, -440, -455, -26, None, None, None, -480, 544, -97, 160, -8, 4, 2309, 160, -24, 1764, 6783, 8547
    ],
    "Q2-2020": [
        129, None, 567, 347, 167, -246, 964, -546, -20, -5, None, None, -566, 164, -71, 18, -6, None, 4973, 57, 38, 559, 8547, 9106
    ],
    "Q3-2020": [
        369, None, 584, 543, 269, 635, 2400, -1005, -16, None, None, -13, -1039, -630, -56, 99, -31, -42, 4973, 144, 86, 5897, 9106, 15003
    ],
    "Q4-2020": [
        296, None, 618, 633, 230, 1242, 3019, -1151, -13, -5, 122, None, -1047, -2074, -16, -215, 0, -46, 4987, 56, 234, 4898, 15003, 19901
    ]
}

# Adjusting the length of each column to ensure consistency
max_length = max(len(cash_flow_data[key]) for key in cash_flow_data)

for key in cash_flow_data:
    while len(cash_flow_data[key]) < max_length:
        cash_flow_data[key].append(None)

# Convert to DataFrame
cash_flow_df = pd.DataFrame(cash_flow_data)

# Save DataFrame to CSV
cash_flow_csv_path = "cash_flow_2020.csv"
cash_flow_df.to_csv(cash_flow_csv_path, index=False)

cash_flow_csv_path

'cash_flow_2020.csv'

In [26]:
# Clean and organize the extracted text into structured data
cash_flow_data_2021 = {
    "Description": [
        "Net income",
        "Adjustments to reconcile net income to net cash provided by operating activities:",
        "Depreciation, amortization and impairment",
        "Stock-based compensation",
        "Other",
        "Changes in operating assets and liabilities, net of effect of business combinations",
        "Net cash provided by operating activities",
        "Capital expenditures",
        "Purchases of solar energy systems, net of sales",
        "Purchases of digital assets",
        "Proceeds from sales of digital assets",
        "Purchases of marketable securities",
        "Receipt of government grants",
        "Purchase of intangible assets",
        "Net cash used in investing activities",
        "Net cash flows from other debt activities",
        "Collateralized lease repayments",
        "Net (repayments) borrowings under vehicle and energy product financing",
        "Net cash flows from noncontrolling interests - Solar",
        "Proceeds from issuances of common stock in public offerings, net of issuance costs",
        "Other",
        "Net cash provided by (used in) financing activities",
        "Effect of exchange rate changes on cash and cash equivalents and restricted cash",
        "Net increase (decrease) in cash and cash equivalents and restricted cash",
        "Cash and cash equivalents and restricted cash at beginning of period",
        "Cash and cash equivalents and restricted cash at end of period"
    ],
    "Q4-2020": [
        296, None, 618, 633, 230, 1242, 3019, -1151, -13, None, None, None, 122, -5, -1047, -2074, -16, -215, None, 4987, 56, 2692, 234, 4898, 15003, 19901
    ],
    "Q1-2021": [
        464, None, 621, 614, -46, -12, 1641, -1348, -12, -1500, 272, None, 6, None, -2582, -1557, -6, 396, None, None, 183, -221, -2178, 19901, 17723
    ],
    "Q2-2021": [
        1178, None, 681, 474, 115, -324, 2124, -1505, None, None, None, None, None, None, -1515, -1230, -1, -356, None, None, 70, 42, -898, 17723, 16825
    ],
    "Q3-2021": [
        1659, None, 761, 475, 253, -1, 3147, -1819, -6, None, None, None, None, None, -1855, -2091, -2, 562, None, None, 192, -42, -131, 16825, 16694
    ],
    "Q4-2021": [
        2343, None, 848, 558, -19, 855, 4585, -1810, -4, None, None, None, None, None, -1916, -860, -1, -596, None, None, 262, 38, 1450, 16694, 18144
    ]
}

# Adjusting the length of each column to ensure consistency
max_length_2021 = max(len(cash_flow_data_2021[key]) for key in cash_flow_data_2021)

for key in cash_flow_data_2021:
    while len(cash_flow_data_2021[key]) < max_length_2021:
        cash_flow_data_2021[key].append(None)

# Convert to DataFrame
cash_flow_df_2021 = pd.DataFrame(cash_flow_data_2021)

# Save DataFrame to CSV
cash_flow_csv_path_2021 = "cash_flow_2021.csv"
cash_flow_df_2021.to_csv(cash_flow_csv_path_2021, index=False)

cash_flow_csv_path_2021

'cash_flow_2021.csv'

In [27]:
# Clean and organize the extracted text into structured data
cash_flow_data_2022 = {
    "Description": [
        "Net income",
        "Adjustments to reconcile net income to net cash provided by operating activities:",
        "Depreciation, amortization and impairment",
        "Stock-based compensation",
        "Other",
        "Changes in operating assets and liabilities, net of effect of business combinations",
        "Net cash provided by operating activities",
        "Capital expenditures",
        "Purchases of solar energy systems, net of sales",
        "Proceeds from sales of digital assets",
        "Purchases of investments",
        "Proceeds from maturities of investments",
        "Receipt of government grants",
        "Purchase of intangible assets",
        "Net cash used in investing activities",
        "Net cash flows from other debt activities",
        "Net (repayments) borrowings under vehicle and energy product financing",
        "Net cash flows from noncontrolling interests - Solar",
        "Other",
        "Net cash provided by (used in) financing activities",
        "Effect of exchange rate changes on cash and cash equivalents and restricted cash",
        "Net increase (decrease) in cash and cash equivalents and restricted cash",
        "Cash and cash equivalents and restricted cash at beginning of period",
        "Cash and cash equivalents and restricted cash at end of period"
    ],
    "Q4-2021": [
        2343, None, 848, 558, -19, 855, 4585, -1810, -4, None, None, None, None, None, -1916, -860, -596, -63, 262, 123, 1450, 16694, 18144
    ],
    "Q1-2022": [
        3280, None, 880, 418, 19, -602, 3995, -1767, -5, None, None, None, None, -9, -2167, -1436, -632, -48, 202, 38, -104, 18144, 18040
    ],
    "Q2-2022": [
        2269, None, 922, 361, 145, -1346, 2351, -1730, 0, None, None, None, None, None, -884, -154, -632, -248, -42, 202, -214, 847, 18887, 20149
    ],
    "Q3-2022": [
        3331, None, 956, 362, 220, 231, 5100, -1803, 0, None, None, None, 3, None, -2791, -133, -766, -42, 229, -335, 1262, 20149, 18887
    ],
    "Q4-2022": [
        3707, None, 989, 419, 354, -2191, 3278, -1858, 0, None, None, None, 76, None, -6131, -162, -335, -65, 67, -495, 3225, 20149, 16924
    ]
}

# Adjusting the length of each column to ensure consistency
max_length_2022 = max(len(cash_flow_data_2022[key]) for key in cash_flow_data_2022)

for key in cash_flow_data_2022:
    while len(cash_flow_data_2022[key]) < max_length_2022:
        cash_flow_data_2022[key].append(None)

# Convert to DataFrame
cash_flow_df_2022 = pd.DataFrame(cash_flow_data_2022)

# Save DataFrame to CSV
cash_flow_csv_path_2022 = "cash_flow_2022.csv"
cash_flow_df_2022.to_csv(cash_flow_csv_path_2022, index=False)

cash_flow_csv_path_2022

'cash_flow_2022.csv'

In [28]:
# Load the CSV files for 2020, 2021, and 2022
csv_2020_path = "cash_flow_2020.csv"
csv_2021_path = "cash_flow_2021.csv"
csv_2022_path = "cash_flow_2022.csv"

df_2020 = pd.read_csv(csv_2020_path)
df_2021 = pd.read_csv(csv_2021_path)
df_2022 = pd.read_csv(csv_2022_path)

# Combine the dataframes
combined_cash_flow_df = pd.concat([df_2020, df_2021, df_2022])

# Remove duplicates
combined_cash_flow_df = combined_cash_flow_df.drop_duplicates()

# Save the combined dataframe to a new CSV file
combined_cash_flow_csv_path = "Cash_flow.csv"
combined_cash_flow_df.to_csv(combined_cash_flow_csv_path, index=False)

combined_cash_flow_csv_path

'Cash_flow.csv'

Tesla_Income_Statement

In [29]:
# Clean and organize the extracted text into structured data
income_statement_data = {
    "Description": [
        "Automotive sales",
        "Automotive leasing",
        "Total automotive revenue",
        "Energy generation and storage",
        "Services and other",
        "Total revenues",
        "Automotive sales (cost of revenues)",
        "Automotive leasing (cost of revenues)",
        "Total automotive cost of revenues",
        "Energy generation and storage (cost of revenues)",
        "Services and other (cost of revenues)",
        "Total cost of revenues",
        "Gross profit",
        "Research and development",
        "Selling, general and administrative",
        "Restructuring and other",
        "Total operating expenses",
        "Income from operations",
        "Interest income",
        "Interest expense",
        "Other (expense) income, net",
        "Income before income taxes",
        "Provision for income taxes",
        "Net income",
        "Net income attributable to noncontrolling interests",
        "Net income attributable to common stockholders",
        "Less: Buy-out of noncontrolling interest",
        "Net income used in computing net income per share of common stock",
        "Net income per share of common stock - Basic",
        "Net income per share of common stock - Diluted",
        "Weighted average shares used in computing net income per share of common stock - Basic",
        "Weighted average shares used in computing net income per share of common stock - Diluted"
    ],
    "Q4-2019": [
        6143, 225, 6368, 436, 580, 7384, 4815, 119, 4934, 385, 674, 5993, 1391, 345, 699, -12, 1032, 359, 10, -170, -25, 174, 42, 132, 27, 105, None, 105, 0.12, 0.11, 902, 935
    ],
    "Q1-2020": [
        4893, 239, 5132, 293, 560, 5985, 3699, 122, 3821, 282, 648, 4751, 1234, 324, 627, 0, 951, 283, 10, -169, -54, 70, 2, 68, 52, 16, None, 16, 0.02, 0.02, 915, 994
    ],
    "Q2-2020": [
        4911, 268, 5179, 370, 487, 6036, 3714, 148, 3862, 349, 558, 4769, 1267, 279, 661, 0, 940, 327, 8, -170, -15, 150, 21, 129, 25, 104, None, 104, 0.11, 0.10, 928, 1036
    ],
    "Q3-2020": [
        7346, 265, 7611, 579, 581, 8771, 5361, 145, 5506, 558, 644, 6708, 2063, 366, 888, 0, 1254, 809, 6, -163, -97, 555, 186, 369, 38, 331, None, 300, 0.32, 0.27, 937, 1105
    ],
    "Q4-2020": [
        9034, 280, 9314, 752, 678, 10744, 6922, 148, 7070, 787, 821, 8678, 2066, 522, 969, 0, 1491, 575, 6, -246, 44, 379, 83, 296, 26, 270, None, 270, 0.28, 0.24, 951, 1124
    ]
}

# Convert to DataFrame
income_statement_df = pd.DataFrame(income_statement_data)

# Save DataFrame to CSV
income_statement_csv_path = "income_statement_2020.csv"
income_statement_df.to_csv(income_statement_csv_path, index=False)

income_statement_csv_path

'income_statement_2020.csv'

In [30]:
# Clean and organize the extracted text into structured data
income_statement_data_2021 = {
    "Description": [
        "Automotive sales",
        "Automotive leasing",
        "Total automotive revenue",
        "Energy generation and storage",
        "Services and other",
        "Total revenues",
        "Automotive sales (cost of revenues)",
        "Automotive leasing (cost of revenues)",
        "Total automotive cost of revenues",
        "Energy generation and storage (cost of revenues)",
        "Services and other (cost of revenues)",
        "Total cost of revenues",
        "Gross profit",
        "Research and development",
        "Selling, general and administrative",
        "Restructuring and other",
        "Total operating expenses",
        "Income from operations",
        "Interest income",
        "Interest expense",
        "Other (expense) income, net",
        "Income before income taxes",
        "Provision for income taxes",
        "Net income",
        "Net income attributable to noncontrolling interests",
        "Net income attributable to common stockholders",
        "Net income per share of common stock - Basic",
        "Net income per share of common stock - Diluted",
        "Weighted average shares used in computing net income per share of common stock - Basic",
        "Weighted average shares used in computing net income per share of common stock - Diluted"
    ],
    "Q4-2020": [
        9034, 280, 9314, 752, 678, 10744, 6922, 148, 7070, 787, 821, 8678, 2066, 522, 969, 0, 1491, 575, 6, -246, 44, 379, 83, 296, 26, 270, 0.28, 0.24, 951, 1124
    ],
    "Q1-2021": [
        8705, 297, 9002, 494, 893, 10389, 6457, 160, 6617, 595, 962, 8174, 2215, 666, 1056, None, 1621, 594, 11, -99, 28, 533, 69, 464, 26, 438, 0.46, 0.39, 961, 1133
    ],
    "Q2-2021": [
        9874, 332, 10206, 801, 951, 11958, 7119, 188, 7307, 781, 986, 9074, 2884, 576, 973, 23, 1572, 1312, 11, -75, 45, 1293, 115, 1178, 36, 1142, 1.18, 1.02, 971, 1119
    ],
    "Q3-2021": [
        11672, 385, 12057, 806, 894, 13757, 8150, 234, 8384, 803, 910, 10097, 3660, 611, 994, 51, 1656, 2004, 10, -126, -6, 1882, 223, 1659, 41, 1618, 1.62, 1.44, 998, 1123
    ],
    "Q4-2021": [
        15339, 628, 15967, 688, 1064, 17719, 10689, 396, 11085, 739, 1048, 12872, 4847, 740, 1494, None, 2234, 2613, 25, -71, 68, 2635, 292, 2343, 22, 2321, 2.29, 2.05, 1015, 1135
    ]
}

# Convert to DataFrame
income_statement_df_2021 = pd.DataFrame(income_statement_data_2021)

# Save DataFrame to CSV
income_statement_csv_path_2021 = "income_statement_2021.csv"
income_statement_df_2021.to_csv(income_statement_csv_path_2021, index=False)

income_statement_csv_path_2021

'income_statement_2021.csv'

In [31]:
# Clean and organize the extracted text into structured data
income_statement_data_2022 = {
    "Description": [
        "Automotive sales",
        "Automotive regulatory credits",
        "Automotive leasing",
        "Total automotive revenue",
        "Energy generation and storage",
        "Services and other",
        "Total revenues",
        "Automotive sales (cost of revenues)",
        "Automotive leasing (cost of revenues)",
        "Total automotive cost of revenues",
        "Energy generation and storage (cost of revenues)",
        "Services and other (cost of revenues)",
        "Total cost of revenues",
        "Gross profit",
        "Research and development",
        "Selling, general and administrative",
        "Restructuring and other",
        "Total operating expenses",
        "Income from operations",
        "Interest income",
        "Interest expense",
        "Other (expense) income, net",
        "Income before income taxes",
        "Provision for income taxes",
        "Net income",
        "Net income attributable to noncontrolling interests",
        "Net income attributable to common stockholders",
        "Net income per share of common stock - Basic",
        "Net income per share of common stock - Diluted",
        "Weighted average shares used in computing net income per share of common stock - Basic",
        "Weighted average shares used in computing net income per share of common stock - Diluted"
    ],
    "Q4-2021": [
        15025, 314, 628, 15967, 688, 1064, 17719, 10689, 396, 11085, 739, 1048, 12872, 4847, 740, 1494, None, 2234, 2613, 25, -71, 68, 2635, 292, 2343, 22, 2321, 0.76, 0.68, 3044, 3472
    ],
    "Q1-2022": [
        15514, 679, 668, 16861, 616, 1279, 18756, 10914, 408, 11522, 688, 1048, 13296, 5460, 865, 992, None, 1857, 3603, 28, -61, 56, 3626, 346, 3280, 38, 3318, 1.07, 0.95, 3103, 3406
    ],
    "Q2-2022": [
        13670, 344, 588, 14602, 866, 1466, 16934, 10153, 368, 10521, 769, 1410, 12700, 4234, 667, 961, 142, 1770, 2464, 26, -44, 28, 2474, 205, 2269, 10, 2259, 0.73, 0.65, 3111, 3464
    ],
    "Q3-2022": [
        17785, 286, 621, 18692, 1117, 1645, 21454, 13099, 381, 13480, 1013, 1579, 16072, 5382, 733, 961, 142, 1694, 3688, 26, -53, -85, 3674, 305, 3311, 39, 3292, 1.05, 0.95, 3146, 3468
    ],
    "Q4-2022": [
        20241, 467, 599, 21307, 1310, 1701, 24318, 15433, 352, 15785, 1151, 1605, 18541, 5777, 810, 1032, 34, 1876, 3901, 157, -33, -42, 3983, 276, 3707, 20, 3687, 1.18, 1.07, 3160, 3471
    ]
}

# Convert to DataFrame
income_statement_df_2022 = pd.DataFrame(income_statement_data_2022)

# Save DataFrame to CSV
income_statement_csv_path_2022 = "income_statement_2022.csv"
income_statement_df_2022.to_csv(income_statement_csv_path_2022, index=False)

income_statement_csv_path_2022

'income_statement_2022.csv'

In [32]:
# Load the CSV files for 2020, 2021, and 2022
csv_2020_income_path = "income_statement_2020.csv"
csv_2021_income_path = "income_statement_2021.csv"
csv_2022_income_path = "income_statement_2022.csv"

df_income_2020 = pd.read_csv(csv_2020_income_path)
df_income_2021 = pd.read_csv(csv_2021_income_path)
df_income_2022 = pd.read_csv(csv_2022_income_path)

# Combine the dataframes
combined_income_statement_df = pd.concat([df_income_2020, df_income_2021, df_income_2022])

# Remove duplicates
combined_income_statement_df = combined_income_statement_df.drop_duplicates()

# Save the combined dataframe to a new CSV file
combined_income_statement_csv_path = "Income_statement.csv"
combined_income_statement_df.to_csv(combined_income_statement_csv_path, index=False)

combined_income_statement_csv_path

'Income_statement.csv'

Tesla_Data

In [33]:
# Attempting to load the CSV files again to handle any previous issues
balance_sheet_df = pd.read_csv('balance_sheet.csv')
cash_flow_df = pd.read_csv('Cash_flow.csv')
income_statement_df = pd.read_csv('Income_statement.csv')
tsla_stock_data_df = pd.read_csv('TSLA.csv')

# Display the first few rows of each DataFrame to understand their structure
balance_sheet_df.head(), cash_flow_df.head(), income_statement_df.head(), tsla_stock_data_df.head()

(                                 Description  31-Dec-19  31-Mar-20  30-Jun-20  \
 0                  Cash and cash equivalents     6268.0     8080.0     8615.0
 1                   Accounts receivable, net     1324.0     1274.0     1485.0
 2                                  Inventory     3552.0     4494.0     4018.0
 3  Prepaid expenses and other current assets      959.0     1045.0     1218.0
 4                       Total current assets    12103.0    14893.0    15336.0

    30-Sep-20  31-Dec-20  31-Mar-21  30-Jun-21  30-Sep-21  31-Dec-21  \
 0    14531.0    19384.0        NaN        NaN        NaN        NaN
 1     1757.0     1886.0        NaN        NaN        NaN        NaN
 2     4218.0     4101.0        NaN        NaN        NaN        NaN
 3     1238.0     1346.0        NaN        NaN        NaN        NaN
 4    21744.0    26717.0        NaN        NaN        NaN        NaN

    31-Mar-22  30-Jun-22  30-Sep-22  31-Dec-22
 0        NaN        NaN        NaN        NaN
 1        NaN        NaN        NaN        NaN
 2        NaN        NaN        NaN        NaN
 3        NaN        NaN        NaN        NaN
 4        NaN        NaN        NaN        NaN  ,
                                          Description  Q4-2019  Q1-2020  \
 0                                         Net income    132.0     68.0
 1  Adjustments to reconcile net income to net cas...      NaN      NaN
 2          Depreciation, amortization and impairment    577.0    553.0
 3                           Stock-based compensation    281.0    211.0
 4                                              Other    204.0    175.0

    Q2-2020  Q3-2020  Q4-2020  Q1-2021  Q2-2021  Q3-2021  Q4-2021  Q1-2022  \
 0    129.0    369.0    296.0      NaN      NaN      NaN      NaN      NaN
 1      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 2    567.0    584.0    618.0      NaN      NaN      NaN      NaN      NaN
 3    347.0    543.0    633.0      NaN      NaN      NaN      NaN      NaN
 4    167.0    269.0    230.0      NaN      NaN      NaN      NaN      NaN

    Q2-2022  Q3-2022  Q4-2022
 0      NaN      NaN      NaN
 1      NaN      NaN      NaN
 2      NaN      NaN      NaN
 3      NaN      NaN      NaN
 4      NaN      NaN      NaN  ,
                      Description  Q4-2019  Q1-2020  Q2-2020  Q3-2020  Q4-2020  \
 0               Automotive sales   6143.0   4893.0   4911.0   7346.0   9034.0
 1             Automotive leasing    225.0    239.0    268.0    265.0    280.0
 2       Total automotive revenue   6368.0   5132.0   5179.0   7611.0   9314.0
 3  Energy generation and storage    436.0    293.0    370.0    579.0    752.0
 4             Services and other    580.0    560.0    487.0    581.0    678.0

    Q1-2021  Q2-2021  Q3-2021  Q4-2021  Q1-2022  Q2-2022  Q3-2022  Q4-2022
 0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 1      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 2      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 3      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
 4      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN  ,
          Date       Open       High        Low      Close  Adj Close  \
 0  2020-01-02  28.299999  28.713333  28.114000  28.684000  28.684000
 1  2020-01-03  29.366667  30.266666  29.128000  29.534000  29.534000
 2  2020-01-06  29.364668  30.104000  29.333332  30.102667  30.102667
 3  2020-01-07  30.760000  31.441999  30.224001  31.270666  31.270666
 4  2020-01-08  31.580000  33.232666  31.215334  32.809334  32.809334

       Volume
 0  142981500
 1  266677500
 2  151995000
 3  268231500
 4  467164500  )

In [34]:
import pandas as pd

# Load the new CSV files
balance_sheet_df = pd.read_csv('balance_sheet.csv')
cash_flow_df = pd.read_csv('Cash_flow.csv')
income_statement_df = pd.read_csv('Income_statement.csv')
tsla_daily_df = pd.read_csv('TSLA.csv')

# Convert 'Date' column in TSLA data to datetime
tsla_daily_df['Date'] = pd.to_datetime(tsla_daily_df['Date'])

# Ensure that 'Date' is set as the index before resampling
tsla_daily_df.set_index('Date', inplace=True)

# Resample TSLA data to quarterly based on 'Date'
tsla_quarterly_df = tsla_daily_df['Close'].resample('Q').mean().reset_index()

# Display the first few rows of the resampled quarterly data
tsla_quarterly_df.head()

        Date       Close
0 2020-03-31   41.455441
1 2020-06-30   54.097365
2 2020-09-30  118.069135
3 2020-12-31  170.650364
4 2021-03-31  251.061967

In [35]:
import pandas as pd

# Load the CSV files (update these paths with your actual file locations)
balance_sheet_df = pd.read_csv('balance_sheet.csv')
cash_flow_df = pd.read_csv('Cash_flow.csv')
income_statement_df = pd.read_csv('Income_statement.csv')
tsla_stock_data_df = pd.read_csv('TSLA.csv')

# Function to convert quarter strings to date format
def convert_quarter_to_date(quarter_str):
    if isinstance(quarter_str, str) and '-' in quarter_str:
        parts = quarter_str.split('-')
        if len(parts) == 2:
            quarter, year = parts
            try:
                year = int(year)
                if quarter == 'Q1':
                    return f'{year}-03-31'
                elif quarter == 'Q2':
                    return f'{year}-06-30'
                elif quarter == 'Q3':
                    return f'{year}-09-30'
                elif quarter == 'Q4':
                    return f'{year}-12-31'
            except ValueError:
                pass
    return None

# Only proceed if the dataframes are not empty
if not balance_sheet_df.empty and not cash_flow_df.empty and not income_statement_df.empty and not tsla_stock_data_df.empty:
    # Apply conversion to the first column of each dataframe and drop rows where conversion fails
    balance_sheet_df['Date'] = balance_sheet_df.iloc[:, 0].apply(convert_quarter_to_date)
    cash_flow_df['Date'] = cash_flow_df.iloc[:, 0].apply(convert_quarter_to_date)
    income_statement_df['Date'] = income_statement_df.iloc[:, 0].apply(convert_quarter_to_date)

    balance_sheet_df = balance_sheet_df.dropna(subset=['Date'])
    cash_flow_df = cash_flow_df.dropna(subset=['Date'])
    income_statement_df = income_statement_df.dropna(subset=['Date'])

    # Convert the 'Date' column in TSLA data to datetime
    tsla_stock_data_df['Date'] = pd.to_datetime(tsla_stock_data_df['Date'])

    # Group TSLA data by quarter and calculate the mean (or sum, depending on the metric)
    tsla_stock_data_df = tsla_stock_data_df.resample('Q', on='Date').mean()

    # Convert the quarterly data to the same format as the financial data
    tsla_stock_data_df.index = tsla_stock_data_df.index.to_series().apply(lambda x: x.strftime('%Y-%m-%d'))

    # Drop the original quarter columns
    balance_sheet_df.drop(balance_sheet_df.columns[0], axis=1, inplace=True)
    cash_flow_df.drop(cash_flow_df.columns[0], axis=1, inplace=True)
    income_statement_df.drop(income_statement_df.columns[0], axis=1, inplace=True)

    # Set 'Date' as the index for merging
    balance_sheet_df.set_index('Date', inplace=True)
    cash_flow_df.set_index('Date', inplace=True)
    income_statement_df.set_index('Date', inplace=True)
    tsla_stock_data_df.index.name = 'Date'

    # Merge the financial dataframes on the 'Date' index
    merged_financial_df = pd.merge(balance_sheet_df, cash_flow_df, left_index=True, right_index=True, how='inner')
    merged_financial_df = pd.merge(merged_financial_df, income_statement_df, left_index=True, right_index=True, how='inner')

    # Merge the financial data with stock data on the 'Date' index
    merged_df = pd.merge(merged_financial_df, tsla_stock_data_df, left_index=True, right_index=True, how='inner')

    # Save the merged dataframe to a new CSV file
    output_file_path = 'Merged_Financial_Stock_Data.csv'
    merged_df.to_csv(output_file_path, index=True)

    print(f'Merged data saved to {output_file_path}')
else:
    print("One or more files are empty. Please ensure the files contain data.")

Merged data saved to Merged_Financial_Stock_Data.csv

In [36]:
# Identify common dates between the financial data and TSLA data
common_dates = set(income_statement_long['Date']).intersection(set(balance_sheet_long['Date'])).intersection(set(cash_flow_long['Date'])).intersection(set(tsla_quarterly_df['Date']))

# Filter the data based on common dates
income_statement_filtered = income_statement_long[income_statement_long['Date'].isin(common_dates)]
balance_sheet_filtered = balance_sheet_long[balance_sheet_long['Date'].isin(common_dates)]
cash_flow_filtered = cash_flow_long[cash_flow_long['Date'].isin(common_dates)]
tsla_filtered = tsla_quarterly_df[tsla_quarterly_df['Date'].isin(common_dates)]

# Fill missing values with zeros
income_statement_filtered.fillna(0, inplace=True)
balance_sheet_filtered.fillna(0, inplace=True)
cash_flow_filtered.fillna(0, inplace=True)

# Merge the financial data on 'Date'
merged_financial_df = pd.merge(income_statement_filtered, balance_sheet_filtered, on='Date', suffixes=('_income', '_balance'))
merged_financial_df = pd.merge(merged_financial_df, cash_flow_filtered, on='Date', suffixes=('', '_cashflow'))

# Merge the quarterly stock data with the financial data
merged_df = pd.merge(merged_financial_df, tsla_filtered, on='Date')

# Drop rows with any remaining missing values
merged_df = merged_df.dropna()

#import ace_tools as tools; tools.display_dataframe_to_user(name="Merged Financial and Quarterly Stock Data", dataframe=merged_df)

# Display the first few rows of the merged dataframe
merged_df.head()

<ipython-input-36-5564bb319d94>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  income_statement_filtered.fillna(0, inplace=True)
<ipython-input-36-5564bb319d94>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  balance_sheet_filtered.fillna(0, inplace=True)
<ipython-input-36-5564bb319d94>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cash_flow_filtered.fillna(0, inplace=True)

,Date,Automotive leasing,Automotive leasing cost of revenues,Automotive sales,Automotive sales cost of revenues,Energy generation and storage,Energy generation and storage cost of revenues,Gross profit,Income before income taxes,Income from operations,...,Net cash used in investing activities,Net income_cashflow,Net increase in cash and cash equivalents and restricted cash,Other,"Proceeds from issuances of common stock in public offerings, net of issuance costs",Purchase of intangible assets,"Purchases of solar energy systems, net of sales",Receipt of government grants,Stock-based compensation,Close
0,2020-03-31,239.0,122.0,4893.0,3699.0,293.0,282.0,1234.0,70.0,283.0,...,-480.0,68.0,1764.0,167.5,2309.0,0.0,-26.0,1.0,211.0,41.455441
1,2020-06-30,265.0,145.0,4911.0,3714.0,370.0,349.0,1267.0,151.0,327.0,...,-566.0,129.0,559.0,112.0,0.0,-5.0,-20.0,0.0,347.0,54.097365
2,2020-09-30,280.0,148.0,7346.0,5361.0,579.0,287.0,2063.0,555.0,809.0,...,-1039.0,369.0,5897.0,206.5,4973.0,0.0,-16.0,0.0,543.0,118.069135
3,2020-12-31,280.0,148.0,9034.0,6922.0,752.0,787.0,2066.0,379.0,575.0,...,-1047.0,296.0,4898.0,143.0,4987.0,-5.0,-13.0,122.0,633.0,170.650364
4,2021-03-31,297.0,180.0,8705.0,6457.0,494.0,595.0,2215.0,533.0,594.0,...,6.0,464.0,-221.0,-46.0,-32.0,-1500.0,-12.0,272.0,614.0,251.061967

In [37]:
# Identify common dates between the financial data and TSLA data
common_dates = set(income_statement_long['Date']).intersection(set(balance_sheet_long['Date'])).intersection(set(cash_flow_long['Date'])).intersection(set(tsla_quarterly_df['Date']))

# Filter the data based on common dates
income_statement_filtered = income_statement_long[income_statement_long['Date'].isin(common_dates)]
balance_sheet_filtered = balance_sheet_long[balance_sheet_long['Date'].isin(common_dates)]
cash_flow_filtered = cash_flow_long[cash_flow_long['Date'].isin(common_dates)]
tsla_filtered = tsla_quarterly_df[tsla_quarterly_df['Date'].isin(common_dates)]

# Fill missing values with zeros
income_statement_filtered.fillna(0, inplace=True)
balance_sheet_filtered.fillna(0, inplace=True)
cash_flow_filtered.fillna(0, inplace=True)

# Merge the financial data on 'Date'
merged_financial_df = pd.merge(income_statement_filtered, balance_sheet_filtered, on='Date', suffixes=('_income', '_balance'))
merged_financial_df = pd.merge(merged_financial_df, cash_flow_filtered, on='Date', suffixes=('', '_cashflow'))

# Merge the quarterly stock data with the financial data
merged_df = pd.merge(merged_financial_df, tsla_filtered, on='Date')

# Drop rows with any remaining missing values
merged_df = merged_df.dropna()

#import ace_tools as tools; tools.display_dataframe_to_user(name="Merged Financial and Quarterly Stock Data", dataframe=merged_df)

# Display the first few rows of the merged dataframe
merged_df.head()

<ipython-input-37-5564bb319d94>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  income_statement_filtered.fillna(0, inplace=True)
<ipython-input-37-5564bb319d94>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  balance_sheet_filtered.fillna(0, inplace=True)
<ipython-input-37-5564bb319d94>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cash_flow_filtered.fillna(0, inplace=True)

,Date,Automotive leasing,Automotive leasing cost of revenues,Automotive sales,Automotive sales cost of revenues,Energy generation and storage,Energy generation and storage cost of revenues,Gross profit,Income before income taxes,Income from operations,...,Net cash used in investing activities,Net income_cashflow,Net increase in cash and cash equivalents and restricted cash,Other,"Proceeds from issuances of common stock in public offerings, net of issuance costs",Purchase of intangible assets,"Purchases of solar energy systems, net of sales",Receipt of government grants,Stock-based compensation,Close
0,2020-03-31,239.0,122.0,4893.0,3699.0,293.0,282.0,1234.0,70.0,283.0,...,-480.0,68.0,1764.0,167.5,2309.0,0.0,-26.0,1.0,211.0,41.455441
1,2020-06-30,265.0,145.0,4911.0,3714.0,370.0,349.0,1267.0,151.0,327.0,...,-566.0,129.0,559.0,112.0,0.0,-5.0,-20.0,0.0,347.0,54.097365
2,2020-09-30,280.0,148.0,7346.0,5361.0,579.0,287.0,2063.0,555.0,809.0,...,-1039.0,369.0,5897.0,206.5,4973.0,0.0,-16.0,0.0,543.0,118.069135
3,2020-12-31,280.0,148.0,9034.0,6922.0,752.0,787.0,2066.0,379.0,575.0,...,-1047.0,296.0,4898.0,143.0,4987.0,-5.0,-13.0,122.0,633.0,170.650364
4,2021-03-31,297.0,180.0,8705.0,6457.0,494.0,595.0,2215.0,533.0,594.0,...,6.0,464.0,-221.0,-46.0,-32.0,-1500.0,-12.0,272.0,614.0,251.061967

In [38]:
# Save the merged DataFrame to a CSV file
output_file_path = 'merged_financial_and_stock_data.csv'
merged_df.to_csv(output_file_path, index=False)

output_file_path

'merged_financial_and_stock_data.csv'